# Generated by Django 5.0.7 on 2024-07-27 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewsApp', '0002_alter_post_options_alter_post_categorytype'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='News',
        ),
    ]
