# Generated by Django 5.0.7 on 2024-07-27 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewsApp', '0003_rename_post_news'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News',
            new_name='Post',
        ),
    ]
